### ISSUE TITLE
Could not load library libcudnn_ops_infer.so.8.

### ISSUE THREAD

**Issue by zzy0222** [ZMpursue/LSTM_Write_Poetry#2]
I use paddle-gpu 2.1 to run this code. When I run Generate.py, it raises an error above.
Error appears here.
model = Peom(
        len(word2ix),
        embedding_dim = Config.embedding_dim,
        hidden_dim = Config.hidden_dim
    )
Please tell me how to solve this problem. Thx!!

**Comment by zzy0222** [comment]
> I use paddle-gpu 2.1 to run this code. When I run Generate.py, it raises an error above.
> Error appears here.
> model = Peom(
> len(word2ix),
> embedding_dim = Config.embedding_dim,
> hidden_dim = Config.hidden_dim
> )
> Please tell me how to solve this problem. Thx!!

After restarting, it works...
